// ------------------------------------------------------------------------------
// <auto-generated>
// Dieser Code wurde von einem Tool generiert.
// Laufzeitversion:4.0.30319.34209
// 
// Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
// der Code erneut generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using Microsoft.VisualBasic;

namespace My.Resources
{

    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    /// <summary>
    /// Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        /// Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
      /// Sucht eine lokalisierte Zeichenfolge, die /***********************************************************************************************************************
      /// &apos;* Project: CmisObjectModelLibrary
      /// &apos;* Copyright (c) 2014, Brügmann Software GmbH, Papenburg, All rights reserved
      /// &apos;*
      /// &apos;* Contact: opensource&lt;at&gt;patorg.de
      /// &apos;* 
      /// &apos;* CmisObjectModelLibrary is a VB.NET implementation of the Content Management Interoperability Services (CMIS) standard
      /// &apos;*
      /// &apos;* This file is part of CmisObjectModelLibrary.
      /// &apos;* 
      /// &apos;* This library is free software; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
      /// </summary>
        internal static string cmis
        {
            get
            {
                return ResourceManager.GetString("cmis", resourceCulture);
            }
        }

        /// <summary>
      /// Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
      /// &lt;!--
      /// &apos;* Project: CmisObjectModelLibrary
      /// &apos;* Copyright (c) 2014, Brügmann Software GmbH, Papenburg, All rights reserved
      /// &apos;*
      /// &apos;* Contact: opensource&lt;at&gt;patorg.de
      /// &apos;* 
      /// &apos;* CmisObjectModelLibrary is a VB.NET implementation of the Content Management Interoperability Services (CMIS) standard
      /// &apos;*
      /// &apos;* This file is part of CmisObjectModelLibrary.
      /// &apos;* 
      /// &apos;* This library is free software; you can redistribute it and/or
      /// &apos;* modify it under  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
      /// </summary>
        internal static string EmbeddedFrame
        {
            get
            {
                return ResourceManager.GetString("EmbeddedFrame", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        /// &lt;html&gt;
        /// 	&lt;head&gt;
        /// 		&lt;title&gt;&lt;/title&gt;
        /// 	&lt;/head&gt;
        /// 	&lt;body&gt;
        /// 	
        /// 	&lt;/body&gt;
        /// &lt;/html&gt; ähnelt.
        /// </summary>
        internal static string EmptyPage
        {
            get
            {
                return ResourceManager.GetString("EmptyPage", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die The parameter &apos;{0}&apos; must not be null or empty. ähnelt.
        /// </summary>
        internal static string InvalidArgument
        {
            get
            {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }

        /// <summary>
      /// Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
      /// &lt;!--
      /// &apos;* Project: CmisObjectModelLibrary
      /// &apos;* Copyright (c) 2014, Brügmann Software GmbH, Papenburg, All rights reserved
      /// &apos;*
      /// &apos;* Contact: opensource&lt;at&gt;patorg.de
      /// &apos;* 
      /// &apos;* CmisObjectModelLibrary is a VB.NET implementation of the Content Management Interoperability Services (CMIS) standard
      /// &apos;*
      /// &apos;* This file is part of CmisObjectModelLibrary.
      /// &apos;* 
      /// &apos;* This library is free software; you can redistribute it and/or
      /// &apos;* modify it under  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
      /// </summary>
        internal static string LoginPage
        {
            get
            {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        /// &lt;html&gt;
        /// 	&lt;head&gt;
        /// 		&lt;title&gt;LoginRef&lt;/title&gt;
        /// 	&lt;/head&gt;
        /// 	&lt;body&gt;
        /// 	    &lt;h1&gt;CmisObjectModel Repository Login&lt;/h1&gt;
        ///        &lt;div&gt;
        ///            &lt;p&gt;To provide your credentials for this CMIS repository follow the &lt;a href=&quot;LoginPage.htm&quot;&gt;link&lt;/a&gt;.&lt;/p&gt;
        ///        &lt;/div&gt;
        /// 	&lt;/body&gt;
        /// &lt;/html&gt; ähnelt.
        /// </summary>
        internal static string LoginRefPage
        {
            get
            {
                return ResourceManager.GetString("LoginRefPage", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Method &apos;{0}&apos; is not supported. ähnelt.
        /// </summary>
        internal static string NotSupported
        {
            get
            {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }

        /// <summary>
      /// Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
      /// &lt;!--
      /// &apos;* Project: CmisObjectModelLibrary
      /// &apos;* Copyright (c) 2014, Brügmann Software GmbH, Papenburg, All rights reserved
      /// &apos;*
      /// &apos;* Contact: opensource&lt;at&gt;patorg.de
      /// &apos;* 
      /// &apos;* CmisObjectModelLibrary is a VB.NET implementation of the Content Management Interoperability Services (CMIS) standard
      /// &apos;*
      /// &apos;* This file is part of CmisObjectModelLibrary.
      /// &apos;* 
      /// &apos;* This library is free software; you can redistribute it and/or
      /// &apos;* modify it under  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
      /// </summary>
        internal static string RedirectPreviousPage
        {
            get
            {
                return ResourceManager.GetString("RedirectPreviousPage", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die No class in assembly found that matches the criteria: the class MUST {0} {1}, MUST have a public constructor which accepts the baseUri (System.Uri) parameter and MUST not be an abstract class. ähnelt.
        /// </summary>
        internal static string ServicesImplNotFound
        {
            get
            {
                return ResourceManager.GetString("ServicesImplNotFound", resourceCulture);
            }
        }
    }
}