
/* TODO ERROR: Skipped EndIfDirectiveTrivia
#End If
*/
namespace CmisObjectModel.Messaging
{
    [Attributes.JavaScriptConverter(typeof(JSON.Messaging.cmisObjectInFolderTypeConverter))]
    public partial class cmisObjectInFolderType
    {
    }
}

namespace CmisObjectModel.JSON.Messaging
{
    [Attributes.AutoGenerated()]
    public partial class cmisObjectInFolderTypeConverter : Serialization.Generic.JavaScriptConverter<CmisObjectModel.Messaging.cmisObjectInFolderType>
    {

        #region Constructors
        public cmisObjectInFolderTypeConverter() : base(new Serialization.Generic.DefaultObjectResolver<CmisObjectModel.Messaging.cmisObjectInFolderType>())
        {
        }
        public cmisObjectInFolderTypeConverter(Serialization.Generic.ObjectResolver<CmisObjectModel.Messaging.cmisObjectInFolderType> objectResolver) : base(objectResolver)
        {
        }
        #endregion

        protected override void Deserialize(SerializationContext context)
        {
            context.Object.PathSegment = Read(context.Dictionary, "pathSegment", context.Object.PathSegment);
            context.Object.Object = Read(context, "object", context.Object.Object);
        }

        protected override void Serialize(SerializationContext context)
        {
            if (!string.IsNullOrEmpty(context.Object.PathSegment))
                context.Add("pathSegment", context.Object.PathSegment);
            Write(context, context.Object.Object, "object");
        }
    }
}