
/* TODO ERROR: Skipped EndIfDirectiveTrivia
#End If
*/
namespace CmisObjectModel.Messaging
{
    [Attributes.JavaScriptConverter(typeof(JSON.Messaging.cmisObjectInFolderContainerTypeConverter))]
    public partial class cmisObjectInFolderContainerType
    {
    }
}

namespace CmisObjectModel.JSON.Messaging
{
    [Attributes.AutoGenerated()]
    public partial class cmisObjectInFolderContainerTypeConverter : Serialization.Generic.JavaScriptConverter<CmisObjectModel.Messaging.cmisObjectInFolderContainerType>
    {

        #region Constructors
        public cmisObjectInFolderContainerTypeConverter() : base(new Serialization.Generic.DefaultObjectResolver<CmisObjectModel.Messaging.cmisObjectInFolderContainerType>())
        {
        }
        public cmisObjectInFolderContainerTypeConverter(Serialization.Generic.ObjectResolver<CmisObjectModel.Messaging.cmisObjectInFolderContainerType> objectResolver) : base(objectResolver)
        {
        }
        #endregion

        protected override void Deserialize(SerializationContext context)
        {
            context.Object.ObjectInFolder = Read(context, "object", context.Object.ObjectInFolder);
            context.Object.Children = ReadArray(context, "children", context.Object.Children);
        }

        protected override void Serialize(SerializationContext context)
        {
            Write(context, context.Object.ObjectInFolder, "object");
            WriteArray(context, context.Object.Children, "children");
        }
    }
}