
/* TODO ERROR: Skipped EndIfDirectiveTrivia
#End If
*/
namespace CmisObjectModel.Messaging
{
    [Attributes.JavaScriptConverter(typeof(JSON.Messaging.cmisObjectParentsTypeConverter))]
    public partial class cmisObjectParentsType
    {
    }
}

namespace CmisObjectModel.JSON.Messaging
{
    [Attributes.AutoGenerated()]
    public partial class cmisObjectParentsTypeConverter : Serialization.Generic.JavaScriptConverter<CmisObjectModel.Messaging.cmisObjectParentsType>
    {

        #region Constructors
        public cmisObjectParentsTypeConverter() : base(new Serialization.Generic.DefaultObjectResolver<CmisObjectModel.Messaging.cmisObjectParentsType>())
        {
        }
        public cmisObjectParentsTypeConverter(Serialization.Generic.ObjectResolver<CmisObjectModel.Messaging.cmisObjectParentsType> objectResolver) : base(objectResolver)
        {
        }
        #endregion

        protected override void Deserialize(SerializationContext context)
        {
            context.Object.RelativePathSegment = Read(context.Dictionary, "relativePathSegment", context.Object.RelativePathSegment);
            context.Object.Object = Read(context, "object", context.Object.Object);
        }

        protected override void Serialize(SerializationContext context)
        {
            if (!string.IsNullOrEmpty(context.Object.RelativePathSegment))
                context.Add("relativePathSegment", context.Object.RelativePathSegment);
            Write(context, context.Object.Object, "object");
        }
    }
}