
/* TODO ERROR: Skipped EndIfDirectiveTrivia
#End If
*/
namespace CmisObjectModel.Core
{
    [Attributes.JavaScriptConverter(typeof(JSON.Core.cmisTypeMutabilityCapabilitiesTypeConverter))]
    public partial class cmisTypeMutabilityCapabilitiesType
    {
    }
}

namespace CmisObjectModel.JSON.Core
{
    [Attributes.AutoGenerated()]
    public partial class cmisTypeMutabilityCapabilitiesTypeConverter : Serialization.Generic.JavaScriptConverter<CmisObjectModel.Core.cmisTypeMutabilityCapabilitiesType>
    {

        #region Constructors
        public cmisTypeMutabilityCapabilitiesTypeConverter() : base(new Serialization.Generic.DefaultObjectResolver<CmisObjectModel.Core.cmisTypeMutabilityCapabilitiesType>())
        {
        }
        public cmisTypeMutabilityCapabilitiesTypeConverter(Serialization.Generic.ObjectResolver<CmisObjectModel.Core.cmisTypeMutabilityCapabilitiesType> objectResolver) : base(objectResolver)
        {
        }
        #endregion

        protected override void Deserialize(SerializationContext context)
        {
            context.Object.Create = Read(context.Dictionary, "create", context.Object.Create);
            context.Object.Update = Read(context.Dictionary, "update", context.Object.Update);
            context.Object.Delete = Read(context.Dictionary, "delete", context.Object.Delete);
        }

        protected override void Serialize(SerializationContext context)
        {
            context.Add("create", context.Object.Create);
            context.Add("update", context.Object.Update);
            context.Add("delete", context.Object.Delete);
        }
    }
}