
// ***********************************************************************************************************************
// * Project: CmisObjectModelLibrary
// * Copyright (c) 2014, Brügmann Software GmbH, Papenburg, All rights reserved
// * Author: BSW_BER
// * Contact: opensource<at>patorg.de
// * 
// * CmisObjectModelLibrary is a VB.NET implementation of the Content Management Interoperability Services (CMIS) standard
// *
// * This file is part of CmisObjectModelLibrary.
// * 
// * This library is free software; you can redistribute it and/or
// * modify it under the terms of the GNU Lesser General Public
// * License as published by the Free Software Foundation; either
// * version 3.0 of the License, or (at your option) any later version.
// *
// * This library is distributed in the hope that it will be useful,
// * but WITHOUT ANY WARRANTY; without even the implied warranty of
// * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// * Lesser General Public License for more details.
// *
// * You should have received a copy of the GNU Lesser General Public
// * License along with this library (lgpl.txt).
// * If not, see <http://www.gnu.org/licenses/lgpl.txt>.
// ***********************************************************************************************************************
using CmisObjectModel.Common;
/* TODO ERROR: Skipped EndIfDirectiveTrivia
#End If
*/
namespace CmisObjectModel.Core
{
    [Attributes.JavaScriptConverter(typeof(JSON.Core.cmisChangeEventTypeConverter))]
    public partial class cmisChangeEventType
    {
    }
}

namespace CmisObjectModel.JSON.Core
{
    [Attributes.AutoGenerated()]
    public partial class cmisChangeEventTypeConverter : Serialization.Generic.JavaScriptConverter<CmisObjectModel.Core.cmisChangeEventType>
    {

        #region Constructors
        public cmisChangeEventTypeConverter() : base(new Serialization.Generic.DefaultObjectResolver<CmisObjectModel.Core.cmisChangeEventType>())
        {
        }
        public cmisChangeEventTypeConverter(Serialization.Generic.ObjectResolver<CmisObjectModel.Core.cmisChangeEventType> objectResolver) : base(objectResolver)
        {
        }
        #endregion

        protected override void Deserialize(SerializationContext context)
        {
            context.Object.ChangeTime = Read(context.Dictionary, "changeTime", context.Object.ChangeTime);
            context.Object.ChangeType = ReadEnum(context.Dictionary, "changeType", context.Object.ChangeType);
        }

        protected override void Serialize(SerializationContext context)
        {
            context.Add("changeTime", context.Object.ChangeTime);
            context.Add("changeType", context.Object.ChangeType.GetName());
        }
    }
}