
/* TODO ERROR: Skipped EndIfDirectiveTrivia
#End If
*/
namespace CmisObjectModel.Core
{
    [Attributes.JavaScriptConverter(typeof(JSON.Core.cmisCreatablePropertyTypesTypeConverter))]
    public partial class cmisCreatablePropertyTypesType
    {
    }
}

namespace CmisObjectModel.JSON.Core
{
    [Attributes.AutoGenerated()]
    public partial class cmisCreatablePropertyTypesTypeConverter : Serialization.Generic.JavaScriptConverter<CmisObjectModel.Core.cmisCreatablePropertyTypesType>
    {

        #region Constructors
        public cmisCreatablePropertyTypesTypeConverter() : base(new Serialization.Generic.DefaultObjectResolver<CmisObjectModel.Core.cmisCreatablePropertyTypesType>())
        {
        }
        public cmisCreatablePropertyTypesTypeConverter(Serialization.Generic.ObjectResolver<CmisObjectModel.Core.cmisCreatablePropertyTypesType> objectResolver) : base(objectResolver)
        {
        }
        #endregion

        protected override void Deserialize(SerializationContext context)
        {
            context.Object.CanCreates = ReadEnumArray(context.Dictionary, "canCreate", context.Object.CanCreates);
        }

        protected override void Serialize(SerializationContext context)
        {
            WriteArray(context, context.Object.CanCreates, "canCreate");
        }
    }
}