
/* TODO ERROR: Skipped EndIfDirectiveTrivia
#End If
*/
namespace CmisObjectModel.Core.Security
{
    [Attributes.JavaScriptConverter(typeof(JSON.Core.Security.cmisPermissionDefinitionConverter))]
    public partial class cmisPermissionDefinition
    {
    }
}

namespace CmisObjectModel.JSON.Core.Security
{
    [Attributes.AutoGenerated()]
    public partial class cmisPermissionDefinitionConverter : Serialization.Generic.JavaScriptConverter<CmisObjectModel.Core.Security.cmisPermissionDefinition>
    {

        #region Constructors
        public cmisPermissionDefinitionConverter() : base(new Serialization.Generic.DefaultObjectResolver<CmisObjectModel.Core.Security.cmisPermissionDefinition>())
        {
        }
        public cmisPermissionDefinitionConverter(Serialization.Generic.ObjectResolver<CmisObjectModel.Core.Security.cmisPermissionDefinition> objectResolver) : base(objectResolver)
        {
        }
        #endregion

        protected override void Deserialize(SerializationContext context)
        {
            context.Object.Permission = Read(context.Dictionary, "permission", context.Object.Permission);
            context.Object.Description = Read(context.Dictionary, "description", context.Object.Description);
        }

        protected override void Serialize(SerializationContext context)
        {
            context.Add("permission", context.Object.Permission);
            if (!string.IsNullOrEmpty(context.Object.Description))
                context.Add("description", context.Object.Description);
        }
    }
}