
// ***********************************************************************************************************************
// * Project: CmisObjectModelLibrary
// * Copyright (c) 2014, Brügmann Software GmbH, Papenburg, All rights reserved
// * Author: BSW_BER
// * Contact: opensource<at>patorg.de
// * 
// * CmisObjectModelLibrary is a VB.NET implementation of the Content Management Interoperability Services (CMIS) standard
// *
// * This file is part of CmisObjectModelLibrary.
// * 
// * This library is free software; you can redistribute it and/or
// * modify it under the terms of the GNU Lesser General Public
// * License as published by the Free Software Foundation; either
// * version 3.0 of the License, or (at your option) any later version.
// *
// * This library is distributed in the hope that it will be useful,
// * but WITHOUT ANY WARRANTY; without even the implied warranty of
// * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// * Lesser General Public License for more details.
// *
// * You should have received a copy of the GNU Lesser General Public
// * License along with this library (lgpl.txt).
// * If not, see <http://www.gnu.org/licenses/lgpl.txt>.
// ***********************************************************************************************************************
using CmisObjectModel.Common;
/* TODO ERROR: Skipped EndIfDirectiveTrivia
#End If
*/
namespace CmisObjectModel.Core.Security
{
    [Attributes.JavaScriptConverter(typeof(JSON.Core.Security.cmisPermissionMappingConverter))]
    public partial class cmisPermissionMapping
    {
    }
}

namespace CmisObjectModel.JSON.Core.Security
{
    [Attributes.AutoGenerated()]
    public partial class cmisPermissionMappingConverter : Serialization.Generic.JavaScriptConverter<CmisObjectModel.Core.Security.cmisPermissionMapping>
    {

        #region Constructors
        public cmisPermissionMappingConverter() : base(new Serialization.Generic.DefaultObjectResolver<CmisObjectModel.Core.Security.cmisPermissionMapping>())
        {
        }
        public cmisPermissionMappingConverter(Serialization.Generic.ObjectResolver<CmisObjectModel.Core.Security.cmisPermissionMapping> objectResolver) : base(objectResolver)
        {
        }
        #endregion

        protected override void Deserialize(SerializationContext context)
        {
            context.Object.Permissions = ReadArray(context.Dictionary, "permission", context.Object.Permissions);
            context.Object.Key = ReadEnum(context.Dictionary, "key", context.Object.Key);
        }

        protected override void Serialize(SerializationContext context)
        {
            WriteArray(context, context.Object.Permissions, "permission");
            context.Add("key", context.Object.Key.GetName());
        }
    }
}